# Default values for htcondor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

masterPublicIp: 212.202.201.205
replicaCountWn: 1
storage: 20Gi

imageCcb:
  repository: htcondor/cm
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "8.9.9-el7"

imageSchedd:
  repository: htcondor/submit
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "8.9.9-el7"

imageWn:
  repository: ttedesch/htcondor-execute
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "root6.22-davix-permission"

imageClient:
  repository: htcondor/execute
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "8.9.9-el7"

serviceCcb:
  port: 30618

serviceSchedd:
  port: 31618

resourcesSchedd:             
  requests:
    memory: "500M"
    cpu: "100m" 
  # limits:
    # cpu: 100m
    # memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetMetric: condor_slot_activity_busy
  targetMetricValue: 0.75

nodeSelectorCcb: {"condor": "ccb"}
nodeSelectorSchedd: {"condor": "schedd"}

