apiVersion: v1
kind: Service
metadata:
  name: hub-webui
  labels:
    component: "hub"
spec:
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: {{ .Values.hub.port }}
  selector:
    app: "hub"
  type: NodePort