apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-adapter-example-cm
  namespace: {{ .Values.namespace }}
data:
  prometheus-adapter.yml: | 
    rules:
      - seriesQuery: 'condor_slot_activity_busy'        
        resources:
          template: "<<.Resource>>"
        name:
          matches: "^(.*)"
          as: "${1}"
        metricsQuery: 'avg(<<.Series>>) by (job)' 