# condir mapfile
apiVersion: v1
kind: ConfigMap
metadata:
  name: mapfile
  namespace: {{ .Values.namespace }}
data:
  condormapfile: |
    SCITOKENS https://cms-auth.web.cern.ch/ cms@users.htcondor.org
    PASSWORD (*.) condor
    GSI (.*) anonymous
