# Longhorn setup
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-condor
  namespace: {{ .Values.namespace }}
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
---
# cluster secret
kind: Secret
apiVersion: v1
metadata:
  name: clustersecret
  namespace: {{ .Values.namespace }}
stringData:
  pool_password: dGVzdG1lcGxz
type: Opaque
---
# condir mapfile
apiVersion: v1
kind: ConfigMap
metadata:
  name: mapfile
  namespace: {{ .Values.namespace }}
data:
  condormapfile: |
    SCITOKENS https://cms-auth.web.cern.ch/ cms@users.htcondor.org
    PASSWORD (*.) condor
    GSI (.*) anonymous
---
# longhorn spool
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spool
  namespace:  {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-condor
  resources:
    requests:
      storage: {{ .Values.storage }}
