apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-example-cm
  namespace: {{ .Values.namespace }}
data:
  prometheus.yml: | 
    global:
      scrape_interval: 10s
      evaluation_interval: 10s
    scrape_configs:
      - job_name: 'htcondor-pod'
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_app]
          action: keep
          regex: htcondor-exporter
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
