apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: htcondor-exporter
  labels:
    app: htcondor-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: htcondor-exporter
  template:
    metadata:
      labels:
        app: htcondor-exporter
    spec:
      containers:
      - name: htcondor-exporter
        #image: ttedesch/htcondor-exporter:v3
        image: "{{ .Values.imageExporter.repository }}:{{ .Values.imageExporter.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.imageExporter.pullPolicy }}
        #image: ttedesch/htcondor-exporter:updatedproxy-ok
        env:
        - name: _condor_SEC_CLIENT_AUTHENTICATION_METHODS
          value: PASSWORD
        - name:  _condor_SEC_DEFAULT_ENCRYPTION
          value: REQUIRED
        - name: _condor_SCHEDD_HOST
          value: {{ .Values.masterPublicIp }}:{{ .Values.serviceSchedd.port }}
        - name:  _condor_COLLECTOR_HOST
          value: {{ .Values.masterPublicIp }}:{{ .Values.serviceCcb.port }}
        - name: _condor_SEC_PASSWORD_FILE
          value: /etc/pwd/pool_password
        ports:
        - containerPort: 9118
        command: ["python3", "/root/CondorExporter.py"]
        volumeMounts:
          - name: clustersecret
            mountPath: /etc/pwd
      volumes:
        - name: clustersecret
          secret:
            secretName: clustersecret
            defaultMode: 256
