apiVersion: v1 
kind: Service 
metadata:
  name: schedd
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.serviceSchedd.port }}
      targetPort: {{ .Values.serviceSchedd.port }}
      nodePort: {{ .Values.serviceSchedd.port }}
      protocol: TCP
      name: collector
  selector:
    app.kubernetes.io/name: schedd
