# define a CA to sign certificate
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: condor
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-com
  namespace: condor
spec:
  # Secret names are always required.
  secretName: example-com-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - infn
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: {{ .Values.masterPublicIp }}.xip.io
  isCA: True
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
  - {{ .Values.masterPublicIp }}.xip.io
  - master.condor.svc.cluster.local
  - schedd.condor.svc.cluster.local
  ipAddresses:
    - {{ .Values.masterPublicIp }}
  # Issuer references are always required.
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    #name: letsencrypt-staging
    #kind: ClusterIssuer