apiVersion: v1
kind: ConfigMap
metadata:
  name: wnconfigd
  namespace: {{ .Values.namespace }}
data:
  01_DODAS_Custom: |
    CONDOR_HOST = {{ .Values.masterPublicIp }}
    DAEMON_LIST = MASTER, STARTD
    COLLECTOR_NAME = DODAS-POOL
    COLLECTOR_HOST = $(CONDOR_HOST):{{ .Values.serviceCcb.port }}
    DISCARD_SESSION_KEYRING_ON_STARTUP = False
    ALLOW_WRITE = *
    ALLOW_ADMINISTRATOR = $(CONDOR_HOST)
    ALLOW_OWNER = $(FULL_HOSTNAME), $(ALLOW_ADMINISTRATOR)
    ALLOW_NEGOTIATOR = *
    ALLOW_NEGOTIATOR_SCHEDD = *
    ALLOW_REMOTE_SUBMIT = True
    ALLOW_ADVERTISE = *
    ALLOW_DAEMON = *
    HOSTALLOW_ADMINISTRATOR = $(CONDOR_HOST)
    HOSTALLOW_OWNER = $(FULL_HOSTNAME), $(HOSTALLOW_ADMINISTRATOR)
    SEC_DEFAULT_AUTHENTICATION = REQUIRED
    SEC_DEFAULT_AUTHENTICATION_METHODS = PASSWORD,GSI
    SEC_PASSWORD_FILE = /etc/pwd/pool_password
    SEC_DEFAULT_INTEGRITY = REQUIRED
    SEC_DEFAULT_ENCRYPTION = REQUIRED
    CERTIFICATE_MAPFILE = /home/uwdir/condormapfile
    GSI_DAEMON_DIRECTORY = /etc/grid-security
    CCB_ADDRESS = $(COLLECTOR_HOST)