apiVersion: v1
kind: ConfigMap
metadata:
  name: ccbconfigd
  namespace: condor
data:
  01_DODAS_Custom: |
    CONDOR_HOST = {{ .Values.masterPublicIp }}
    DAEMON_LIST = COLLECTOR, MASTER, NEGOTIATOR
    COLLECTOR_NAME = DODAS-POOL
    COLLECTOR_HOST = $(CONDOR_HOST):{{ .Values.serviceCcb.port }}
    DISCARD_SESSION_KEYRING_ON_STARTUP = False
    HIGHPORT = 31048
    LOWPORT = 31024
    ALLOW_WRITE = *
    ALLOW_ADMINISTRATOR = $(CONDOR_HOST)
    ALLOW_OWNER = $(FULL_HOSTNAME), $(ALLOW_ADMINISTRATOR)
    ALLOW_NEGOTIATOR = *
    ALLOW_NEGOTIATOR_SCHEDD = *
    ALLOW_REMOTE_SUBMIT = True
    ALLOW_ADVERTISE = *
    ALLOW_DAEMON = *
    HOSTALLOW_ADMINISTRATOR = $(CONDOR_HOST)
    HOSTALLOW_OWNER = $(FULL_HOSTNAME), $(HOSTALLOW_ADMINISTRATOR)
    SEC_DEFAULT_AUTHENTICATION = REQUIRED
    SEC_DEFAULT_AUTHENTICATION_METHODS = PASSWORD,SCITOKENS,GSI
    SEC_PASSWORD_FILE = /etc/pwd/pool_password
    SEC_DEFAULT_INTEGRITY = REQUIRED
    SEC_DEFAULT_ENCRYPTION = REQUIRED
    AUTH_SSL_SERVER_CAFILE = /etc/certs/ca.crt
    AUTH_SSL_SERVER_CERTFILE = /etc/certs/tls.crt
    AUTH_SSL_SERVER_KEYFILE = /etc/certs/tls.key
    CERTIFICATE_MAPFILE = /home/uwdir/condormapfile
    GSI_DAEMON_PROXY = /tmp/proxy
    COLLECTOR_DEBUG=D_FULLDEBUG,D_SECURITY,D_NETWORK
    TOOL_DEBUG=D_FULLDEBUG,D_SECURITY
    SHARED_PORT_ARGS = -p {{ .Values.serviceCcb.port }}
    TCP_FORWARDING_HOST = {{ .Values.masterPublicIp }}.xip.io