apiVersion: v1
kind: ConfigMap
metadata:
  name: scheddconfigd
  namespace: condor
data:
  01_DODAS_Custom: |
    CONDOR_HOST = {{ .Values.masterPublicIp }}
    DAEMON_LIST = MASTER, SCHEDD
    COLLECTOR_NAME = DODAS-POOL
    COLLECTOR_HOST = $(CONDOR_HOST):{{ .Values.serviceCcb.port }}
    DISCARD_SESSION_KEYRING_ON_STARTUP = False
    HIGHPORT = 31048
    LOWPORT = 31024
    ALLOW_WRITE = *
    ALLOW_ADMINISTRATOR = $(CONDOR_HOST)
    ALLOW_OWNER = $(FULL_HOSTNAME), $(ALLOW_ADMINISTRATOR)
    ALLOW_NEGOTIATOR = *
    ALLOW_NEGOTIATOR_SCHEDD = *
    ALLOW_REMOTE_SUBMIT = True
    ALLOW_ADVERTISE = *
    ALLOW_DAEMON = *
    HOSTALLOW_ADMINISTRATOR = $(CONDOR_HOST)
    HOSTALLOW_OWNER = $(FULL_HOSTNAME), $(HOSTALLOW_ADMINISTRATOR)
    SEC_DEFAULT_AUTHENTICATION = REQUIRED
    SEC_DEFAULT_AUTHENTICATION_METHODS = PASSWORD,SCITOKENS,GSI
    SEC_DEFAULT_INTEGRITY = REQUIRED
    SEC_DEFAULT_ENCRYPTION = REQUIRED
    CERTIFICATE_MAPFILE = /home/uwdir/condormapfile
    SEC_PASSWORD_FILE = /etc/pwd/pool_password
    GSI_DAEMON_DIRECTORY = /etc/grid-security
    NETWORK_HOSTNAME = schedd.condor.svc.cluster.local
    QUEUE_SUPER_USER_MAY_IMPERSONATE = .*
    QUEUE_SUPER_USERS = condor, cms@users.htcondor.org
    QUEUE_ALL_USERS_TRUSTED = True
    AUTH_SSL_SERVER_CAFILE = /etc/certs/ca.crt
    AUTH_SSL_SERVER_CERTFILE = /etc/certs/tls.crt
    AUTH_SSL_SERVER_KEYFILE = /etc/certs/tls.key
    SCHEDD_AUDIT_LOG = $(LOG)/AuditLog
    SCHEDD_DEBUG=D_FULLDEBUG,D_SECURITY,D_NETWORK
    TOOL_DEBUG=D_FULLDEBUG,D_SECURITY
    MAX_SCHEDD_AUDIT_LOG = 1d
    MAX_NUM_SCHEDD_AUDIT_LOG = 90
    SHARED_PORT_ARGS = -p {{ .Values.serviceSchedd.port }}
    PRIVATE_NETWORK_NAME = schedd.condor.svc.cluster.local
    TCP_FORWARDING_HOST = {{ .Values.masterPublicIp }}.xip.io