apiVersion: v1
appVersion: "1"
description: A Helm chart for the deployment of multi-user JupyterHUB
name: jupyterhub
version: "1"
maintainers:
  - name: ttedesch
    email: tommaso.tedeschi@pg.infn.it
  - name: dciangot
    email: diego.ciangottini@pg.infn.it
